# ------------------------------------------------------------------------------
# SecretProviderClass
#
# Retrieves the Amazon RDS credentials stored in AWS Secrets Manager
# using Amazon EKS Pod Identity.
#
# The Secrets Store CSI Driver synchronizes the credentials into
# a Kubernetes Secret consumed by the Orders microservice.
# ------------------------------------------------------------------------------
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-db-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: us-east-1
    usePodIdentity: "true"
    objects: |
      - objectName: arn:aws:secretsmanager:us-east-1:162663626265:secret:rds!db-f93868c7-6d9c-445d-b38a-572b3900e3a7-DG8zNk
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
  # store the retrieved secrets in a Kubernetes Secret and make them available to the Orders microservice
  secretObjects:
    - secretName: orders-db
      type: Opaque
      data:
        - objectName: username
          key: RETAIL_ORDERS_PERSISTENCE_USERNAME
        - objectName: password
          key: RETAIL_ORDERS_PERSISTENCE_PASSWORD