apiVersion: v1
kind: Pod

metadata:
  name: ebs-test-pod

spec:
  containers:
    - name: app
      image: nginx:stable

      volumeMounts:
        - mountPath: /data
          name: ebs-storage

  volumes:
    - name: ebs-storage

      persistentVolumeClaim:
        claimName: ebs-test-pvc